// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScholaAi.Dados;

#nullable disable

namespace ScholaAi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250601022024_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScholaAi.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("Alternativa");
                });

            modelBuilder.Entity("ScholaAi.Models.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTipoAgente")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agente");
                });

            modelBuilder.Entity("ScholaAi.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstiloAprendizagem")
                        .HasColumnType("text");

                    b.Property<string>("GeneroLiterarioFavorito")
                        .HasColumnType("text");

                    b.Property<string>("Hobbies")
                        .HasColumnType("text");

                    b.Property<string>("HorasEstudo")
                        .HasColumnType("text");

                    b.Property<int>("IdAgente")
                        .HasColumnType("integer");

                    b.Property<int>("IdEducador")
                        .HasColumnType("integer");

                    b.Property<string>("InformacaoAdicional")
                        .HasColumnType("text");

                    b.Property<string>("ModeloEnsino")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("ScholaAi.Models.AlunoAtividadeMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer");

                    b.Property<int>("IdAtividade")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.Property<float?>("Pontuacao")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdAtividade");

                    b.HasIndex("IdMateria");

                    b.ToTable("AlunoAtividadeMateria");
                });

            modelBuilder.Entity("ScholaAi.Models.AlunoGeneroLiterario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGeneroLiterario")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AlunoGeneroLiterario");
                });

            modelBuilder.Entity("ScholaAi.Models.AlunoHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer");

                    b.Property<int>("IdHobby")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AlunoHobby");
                });

            modelBuilder.Entity("ScholaAi.Models.AlunoMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AlunoMateria");
                });

            modelBuilder.Entity("ScholaAi.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoBase64")
                        .HasColumnType("text");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoAtividade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("text");

                    b.Property<float>("Pontuacao")
                        .HasColumnType("real");

                    b.Property<bool>("Publicada")
                        .HasColumnType("boolean");

                    b.Property<string>("TextoLeitura")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Atividade");
                });

            modelBuilder.Entity("ScholaAi.Models.Educador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAgente")
                        .HasColumnType("integer");

                    b.Property<int>("NivelVisibilidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Educador");
                });

            modelBuilder.Entity("ScholaAi.Models.GeneroLiterario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeneroLiterario");
                });

            modelBuilder.Entity("ScholaAi.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hobby");
                });

            modelBuilder.Entity("ScholaAi.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("ScholaAi.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<int>("IdEducadorCriador")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("ScholaAi.Models.MaterialGeneroLiterario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGeneroLiterario")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MaterialGeneroLiterario");
                });

            modelBuilder.Entity("ScholaAi.Models.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<float>("Pontuacao")
                        .HasColumnType("real");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.ToTable("Questao");
                });

            modelBuilder.Entity("ScholaAi.Models.TipoAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoAtividade");
                });

            modelBuilder.Entity("ScholaAi.Alternativa", b =>
                {
                    b.HasOne("ScholaAi.Models.Questao", null)
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholaAi.Models.AlunoAtividadeMateria", b =>
                {
                    b.HasOne("ScholaAi.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.Atividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("IdAtividade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Atividade");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ScholaAi.Models.Questao", b =>
                {
                    b.HasOne("ScholaAi.Models.Atividade", null)
                        .WithMany("Questoes")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholaAi.Models.Atividade", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("ScholaAi.Models.Questao", b =>
                {
                    b.Navigation("Alternativas");
                });
#pragma warning restore 612, 618
        }
    }
}
